name: NPC_Destinations
main: net.livecar.nuttyworks.npc_destinations.DestinationsPlugin
description: Extends Citizens to allow location settings for NPC's with many other options.
version: 2.3.1
depend: [Citizens]
author: Sir_Nutty@Spigot
api-version: 1.13
website: https://www.spigotmc.org/resources/nunpcdestinations-create-living-npcs-1-8-3-1-10-2.13863/
commands:
  npcdest:
    description: Give your citizens NPC's a goal in life.
    aliases: [nd]
    usage:
      /npcdest help
